# Autogenerated wrapper script for GAP_pkg_cvec_jll for aarch64-unknown-freebsd
export cvec

using GAP_jll
JLLWrappers.@generate_wrapper_header("GAP_pkg_cvec")
JLLWrappers.@declare_file_product(cvec)
function __init__()
    JLLWrappers.@generate_init_header(GAP_jll)
    JLLWrappers.@init_file_product(
        cvec,
        "lib/gap/cvec.so",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
